#version: "3.9" #Es un argumneto obsoleto.
#              #Declaramos la version de la especificacion del archivo compose
               #en las versiones actualizadas de docker no es necesario, ya que 
               #lo detecta automaticamente.

services:
  #Desplegamos los servicios del backend en Flask
  backend:
    build: ./backend
    container_name: tienda_flask_backend
    # restart: always
    ports:
      - "5000:5000"
    environment:
      # Variables para que Flask se conecte al MySQL del contenedor
      DB_HOST: db
      DB_USER: mopii
      DB_PASSWORD: daw
      DB_NAME: tienda_forestal
    depends_on:
      - db
 # Espera a que MySQL est√© listo
 #   healthcheck:
 #     test: ["CMD", "python", "-c", "import mysql.connector; mysql.connector.connect(host='db', user='mopii', password='daw', database='tienda_forestal')"]
 #     interval: 10s
 #     timeout: 30s
 #     retries: 5

  #Desplegamos los servicios del frontend
  frontend:
    build: ./frontend
    container_name: tienda_vue_frontend
    # restart: always
    ports:
 #    - "8080:8080"
      - "8080:80"
    depends_on:
      - backend
        
  #Desplegamos los servicios de la base de datos MySQL
  db:
    image: mysql:8.0
    container_name: tienda_mysql_db
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iesmariamoliner
      MYSQL_DATABASE: tienda_forestal
      MYSQL_USER: mopii
      MYSQL_PASSWORD: daw
    ports:
      - "3306:3306"
    volumes:
      # Persistencia de datos
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  #Incluimos el servicio phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_web
    #restart: always
    ports:
      - "8081:80"     # Acceso desde http://localhost:8081 
                      # login:
    environment:
      PMA_HOST: db        # phpMyAdmin debe mirar al contenedor "db" creado con anterioridad
  #   PMA_USER: root
  #   PMA_PASSWORD: iesmariamoliner
      PMA_USER: mopii
      PMA_PASSWORD: daw
    depends_on:
      - db

volumes:
  mysql_data:

